### ISSUE TITLE
fatal: [ios-xe-mgmt.cisco.com]: FAILED! => {"changed": false, "msg": "[Errno 60] Operation timed out"}

### ISSUE THREAD

**Issue by Scorpion2115** [CiscoDevNet/dne-dna-code#113]
I am learning this lab Ansible IOS native modules. But the first task (GATHERING FACTS) of the playbook 02-ios_command_show.yaml is failed due to
```
fatal: [ios-xe-mgmt.cisco.com]: FAILED! => {"changed": false, "msg": "[Errno 60] Operation timed out"}.
```

I also tried different IOS XE sandbox but neither of them are working
```
fatal: [sandbox-iosxe-latest-1.cisco.com]: FAILED! => {"changed": false, "msg": "[Errno 60] Operation timed out"}
fatal: [sandbox-iosxe-recomm-1.cisco.com]: FAILED! => {"changed": false, "msg": "[Errno 60] Operation timed out"}
```

**Comment by annegentle** [comment]
I've merged a PR that updated the `env_lab.py` file with the latest Sandbox value, so I believe this should work now.
